//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbEntityDenemesiEntities : DbContext
    {
        public DbEntityDenemesiEntities()
            : base("name=DbEntityDenemesiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Der> Ders { get; set; }
        public virtual DbSet<Notlar> Notlars { get; set; }
        public virtual DbSet<OgrenciTablosu> OgrenciTablosus { get; set; }
    }
}
